name: Create and Deploy .htpasswd

on:
  push:
    branches:
      - main

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create sensitive file
        run: |
          mkdir -p www/atelier1
          echo "${{ secrets.HTPASSWD_CONTENT }}" > www/atelier1/.htpasswd

      - name: Verify .htpasswd creation
        run: |
          ls -l www/atelier1/
          cat www/atelier1/.htpasswd
